using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Scaffolding.Metadata;
using System;
using System.Collections.Generic;
using System.Text;

namespace Haukcode.Migration.Models
{
    public class Column
    {
        //
        // Summary:
        //     The column name.
        public string Name { get; set; }

        //
        // Summary:
        //     Indicates whether or not this column can contain NULL values.
        public bool IsNullable { get; set; }

        //
        // Summary:
        //     The database/store type of the column.
        public string StoreType { get; set; }

        //
        // Summary:
        //     The default constraint for the column, or null if none.
        public string DefaultValueSql { get; set; }

        //
        // Summary:
        //     The SQL expression that computes the value of the column, or null if this is
        //     not a computed column.
        public string ComputedColumnSql { get; set; }

        //
        // Summary:
        //     Indicates when values will be generated by the database for this column, or null
        //     if the database will not generate values.
        public ValueGenerated? ValueGenerated { get; set; }

        public Column()
        {
        }

        public Column(DatabaseColumn source)
        {
            Name = source.Name;
            IsNullable = source.IsNullable;
            StoreType = source.StoreType;
            DefaultValueSql = source.DefaultValueSql;
            ComputedColumnSql = source.ComputedColumnSql;
            ValueGenerated = source.ValueGenerated;
        }
    }
}
